services:
  techsolutions-web:
    build:
      context: .
    image: techsolutions-web:latest
    container_name: techsolutions-web
    ports:
      - "8081:80"
    depends_on:
      techsolutions-api:
        condition: service_healthy
    networks:
      - techsolutions-net
    restart: unless-stopped

  techsolutions-api:
    build:
      context: ./api
    image: techsolutions-api:latest
    container_name: techsolutions-api
    ports:
      - "5000:5000"
    networks:
      - techsolutions-net
    restart: unless-stopped

networks:
  techsolutions-net:
    name: techsolutions-net
