pipeline {
    agent any

    stages {
        stage('Validar archivos') {
            steps {
                sh '''
                echo "Validando estructura del proyecto..."
                ls -la
                test -f Dockerfile
                test -f index.html
                test -f nginx.conf
                '''
            }
        }

        stage('Construir imagen Docker') {
            steps {
                sh '''
                docker build -t proyectofrontend2025:jenkins .
                '''
            }
        }

        stage('Eliminar contenedor anterior') {
            steps {
                sh '''
                docker rm -f proyecto_frontend_jenkins || true
                '''
            }
        }

        stage('Desplegar contenedor') {
            steps {
                sh '''
                docker run -d -p 8082:80 --name proyecto_frontend_jenkins proyectofrontend2025:jenkins
                '''
            }
        }

        stage('Verificar despliegue') {
            steps {
                sh '''
                docker ps
                '''
            }
        }
    }
}